### ISSUE TITLE
Bootstrap Mashup not working

### ISSUE THREAD

**Issue by qlikviewsense** [qlik-demo-team/qdt-components#219]
Dear ones, i've an issue using this library.

I've just built a simple html page with a Bootstrap 4 tabbed navigation menu ( referencing 2 Divs let's call them Tab1 and Tab2 ) aimed to a Qlik Sense Desktop September 2019

Objects in **Tab1** gets rendered correctly via a serie of renders like the following

`var element = document.getElementById('sh01wp01');
            QdtComponent.render('QdtViz', {
                id: 'VjemR',
                height: '200px'
            }, element);`

Objects in **Tab2** gets rendered partially ( with a similar serie of renders like the one above )
Chrome Console says "WARNING: Tried to load AngularJS more than once." and throws this error 

`qdt-components.js:6 Uncaught (in promise) Invariant Violation: Minified React error #200; visit http://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at i (http://localhost:3000/js/qdt-components.js:6:228169)
    at i (http://localhost:3000/js/qdt-components.js:19:3053)
    at ln (http://localhost:3000/js/qdt-components.js:19:71235)
    at Object.render (http://localhost:3000/js/qdt-components.js:27:28606)
    at http://localhost:3000/js/qdt-components.js:11:12440
    at new Promise (<anonymous>)
    at new t (http://localhost:3000/js/qdt-components.js:1:1873)
    at e.<anonymous> (http://localhost:3000/js/qdt-components.js:11:12355)
    at i (http://localhost:3000/js/qdt-components.js:11:13456)
    at Generator._invoke (http://localhost:3000/js/qdt-components.js:11:14501)`

my scripts loading sequence in html page is 

`    <script type="text/javascript" src="../js/qdt-components.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
`

Any knows issue for this behavior? Any suggestion ( please ) ?
If any example exists, i'd just need to organize my qlik objects in menu categories, maybe bootstrap is not a good choice?

Thank you

**Comment by yianni-ververis** [comment]
Try the latest 3.0
